#!/bin/bash
/opt/IBM/db2/V10.5/adm/db2set DB2_RR_TO_RS=YES
/opt/IBM/db2/V10.5/adm/db2set DB2_EVALUNCOMMITTED=YES
/opt/IBM/db2/V10.5/adm/db2set DB2_INLIST_TO_NLJN=YES

/opt/IBM/db2/V10.5/bin/db2 "UPDATE DBM CFG USING query_heap_sz 32768"
/opt/IBM/db2/V10.5/bin/db2 "UPDATE DBM CFG USING maxagents 600"
/opt/IBM/db2/V10.5/bin/db2 "UPDATE DBM CFG USING sheapthres 0"

for i in RELDB COMDB CUSDB JCRDB FDBKDB LMDB; do

echo "/opt/IBM/db2/V10.5/bin/db2 CREATE DB $i using codeset UTF-8 territory us PAGESIZE 8192"
/opt/IBM/db2/V10.5/bin/db2 "CREATE DB $i using codeset UTF-8 territory us PAGESIZE 8192"
/opt/IBM/db2/V10.5/bin/db2 "UPDATE DB CFG FOR $i USING applheapsz 4096"
/opt/IBM/db2/V10.5/bin/db2 "UPDATE DB CFG FOR $i USING app_ctl_heap_sz 1024"
/opt/IBM/db2/V10.5/bin/db2 "UPDATE DB CFG FOR $i USING stmtheap AUTOMATIC"
/opt/IBM/db2/V10.5/bin/db2 "UPDATE DB CFG FOR $i USING dbheap AUTOMATIC"
/opt/IBM/db2/V10.5/bin/db2 "UPDATE DB CFG FOR $i USING locklist AUTOMATIC"
/opt/IBM/db2/V10.5/bin/db2 "UPDATE DB CFG FOR $i USING logfilsiz 8000"
/opt/IBM/db2/V10.5/bin/db2 "UPDATE DB CFG FOR $i USING logprimary 12"
/opt/IBM/db2/V10.5/bin/db2 "UPDATE DB CFG FOR $i USING logsecond 32"
/opt/IBM/db2/V10.5/bin/db2 "UPDATE DB CFG FOR $i USING logbufsz 128"
/opt/IBM/db2/V10.5/bin/db2 "UPDATE DB CFG FOR $i USING avg_appls 5"
/opt/IBM/db2/V10.5/bin/db2 "UPDATE DB CFG FOR $i USING locktimeout 180"
/opt/IBM/db2/V10.5/bin/db2 "UPDATE DB CFG FOR $i using AUTO_MAINT off"
done

/opt/IBM/db2/V10.5/bin/db2 "UPDATE DB CFG FOR JCRDB USING logfilsiz 32768"
/opt/IBM/db2/V10.5/bin/db2 "UPDATE DB CFG FOR JCRDB USING logprimary 32"
/opt/IBM/db2/V10.5/bin/db2 "CONNECT TO JCRDB"
/opt/IBM/db2/V10.5/bin/db2 "CREATE BUFFERPOOL ICMLSFREQBP4 SIZE 1000 PAGESIZE 4 K"
/opt/IBM/db2/V10.5/bin/db2 "CREATE BUFFERPOOL ICMLSVOLATILEBP4 SIZE 8000 PAGESIZE 4 K"
/opt/IBM/db2/V10.5/bin/db2 "CREATE BUFFERPOOL ICMLSMAINBP32 SIZE 8000 PAGESIZE 32 K"
/opt/IBM/db2/V10.5/bin/db2 "CREATE BUFFERPOOL CMBMAIN4 SIZE 1000 PAGESIZE 4 K"
/opt/IBM/db2/V10.5/bin/db2 "CREATE REGULAR TABLESPACE ICMLFQ32 PAGESIZE 32 K MANAGED BY SYSTEM USING ('ICMLFQ32') BUFFERPOOL ICMLSMAINBP32"
/opt/IBM/db2/V10.5/bin/db2 "CREATE REGULAR TABLESPACE ICMLNF32 PAGESIZE 32 K MANAGED BY SYSTEM USING ('ICMLNF32') BUFFERPOOL ICMLSMAINBP32"
/opt/IBM/db2/V10.5/bin/db2 "CREATE REGULAR TABLESPACE ICMVFQ04 PAGESIZE 4 K MANAGED BY SYSTEM USING ('ICMVFQ04') BUFFERPOOL ICMLSVOLATILEBP4"
/opt/IBM/db2/V10.5/bin/db2 "CREATE REGULAR TABLESPACE ICMSFQ04 PAGESIZE 4 K MANAGED BY SYSTEM USING ('ICMSFQ04') BUFFERPOOL ICMLSFREQBP4"
/opt/IBM/db2/V10.5/bin/db2 "CREATE REGULAR TABLESPACE CMBINV04 PAGESIZE 4 K MANAGED BY SYSTEM USING ('CMBINV04') BUFFERPOOL CMBMAIN4"
/opt/IBM/db2/V10.5/bin/db2 "CREATE SYSTEM TEMPORARY TABLESPACE ICMLSSYSTSPACE32 PAGESIZE 32 K MANAGED BY SYSTEM USING ('icmlssystspace32') BUFFERPOOL ICMLSMAINBP32"
/opt/IBM/db2/V10.5/bin/db2 "CREATE SYSTEM TEMPORARY TABLESPACE ICMLSSYSTSPACE4 PAGESIZE 4 K MANAGED BY SYSTEM USING ('icmlssystspace4') BUFFERPOOL ICMLSVOLATILEBP4"
/opt/IBM/db2/V10.5/bin/db2 "CREATE USER TEMPORARY TABLESPACE ICMLSUSRTSPACE4 PAGESIZE 4 K MANAGED BY SYSTEM USING ('icmlsusrtspace4') BUFFERPOOL ICMLSVOLATILEBP4"
/opt/IBM/db2/V10.5/bin/db2 "DISCONNECT JCRDB"
/opt/IBM/db2/V10.5/bin/db2 "TERMINATE"
