apiVersion: v1
kind: Service
metadata:
  name: jvpo1rednode03-svc
spec:
  selector:
    redis-label: jvpo1rednode03
  ports:
  - name: 'redis-slave'
    port: 6379
    targetPort: 6379
    protocol: TCP
  type: ClusterIP