apiVersion: v1
kind: Service
metadata:
  name: jvpo1redsenti-svc
spec:
  selector:
    redis-label: jvpo1redsenti
  ports:
  - name: 'redis-sentinel'
    port: 26379
    targetPort: 26379
    protocol: TCP
  type: LoadBalancer