apiVersion: v1
kind: Service
metadata:
  name: mfp-farm1-svc
spec:
  selector:
    app: mfp-farm1
  ports:
  - name: 'mfp-http'
    port: 80
    targetPort: 80
    protocol: TCP
  - name: 'mfp-https'
    port: 443
    targetPort: 443
    protocol: TCP
  type: ClusterIP