apiVersion: v1
kind: Service
metadata:
  name: jvp-claro-web-svc
spec:
  selector:
    jvp-label: jvp-claro-web
  ports:
  - name: 'nginx-http'
    port: 80
    nodePort: 30008
    protocol: TCP
  type: NodePort