apiVersion: v1
kind: Service
metadata:
  name: jvp-php-iam-svc
spec:
  selector:
    jvp-label: jvp-php-iam
  ports:
  # - name: 'nginx-http'
  #   port: 80
  #   targetPort: 5222
  #   protocol: TCP
  - name: 'nginx-https'
    port: 443
    nodePort: 30004
    # targetPort: 5222
    protocol: TCP
    #targetPort: 443
  # type: ClusterIP
  type: NodePort