apiVersion: v1
kind: Service
metadata:
  name: jvp-claro-iam-php-svc
spec:
  selector:
    jvp-label: jvp-claro-iam-php
  ports:
  - name: 'nginx-http'
    port: 80
    nodePort: 30006
    protocol: TCP
  type: NodePort