apiVersion: v1
kind: Service
metadata:
  name: jvp-claro-jitsi-meet-svc
spec:
  selector:
    jvp-label: jvp-claro-jitsi-meet
  ports:
  - name: 'nginx-http'
    port: 80
    nodePort: 30007
    protocol: TCP
  type: NodePort