apiVersion: v1
kind: Service
metadata:
  name: jvp-jp-iam-svc
spec:
  selector:
    jvp-label: jvp-jp-iam
  ports:
  - name: "jp-iam-5222"
    port: 5222
    nodePort: 30000
    # targetPort: 5222
    protocol: TCP
  - name: "jp-iam-5280"
    port: 5280
    nodePort: 30001
    # targetPort: 5280
    protocol: TCP
  - name: "jp-iam-5347"
    port: 5347
    nodePort: 30002
    # targetPort: 5347
    protocol: TCP
  # type: ClusterIP
  type: NodePort