apiVersion: v1
kind: Service
metadata:
  name: jvp-claro-iam-front-svc
spec:
  selector:
    jvp-label: jvp-claro-iam-front
  ports:
  - name: 'nginx-http'
    port: 80
    nodePort: 30005
    protocol: TCP
  type: NodePort