# Ejemplo para convertir un archivo a base64 para Openshift

# ~/.docker/config.json
###########################################################
# {
# 	"auths": {
# 		"https://registry.access.redhat.com/v1/": {
# 			"auth": "a2V2b3Bzb2ZpY2lhbDprZXYyMDE2NTk3OQ=="
# 		}
# 	}
# }
###########################################################

# echo -n "$(cat ~/.docker/config.json)" | base64 -w0
apiVersion: v1
data:
  .dockerconfigjson: >-
    ewogCSJhdXRocyI6IHsKCQkibmV4dXMtYWRtaW4uZ2FkdC5hbXhkaWdpdGFsLm5ldCI6IHsKCQkJImF1dGgiOiAiYTJWMmFXNHVaMjl0WlhvNmNtVnVZVGxwWlVKMU5XbGsiCgkJfQoJfQp9
kind: Secret
metadata:
  name: registry-secret
type: kubernetes.io/dockerconfigjson
---
apiVersion: v1
data:
  .dockerconfigjson: >-
    ewoJImF1dGhzIjogewoJCSJkb2NrZXItc291cmNlLXJlZ2lzdHJ5LmFteGRpZ2l0YWwubmV0IjogewoJCQkiYXV0aCI6ICJiMnRsWVc0dGJ5MXRjbXN0YVRwTllYSnJYMlJwYzJOdk9VaHZiR1JtYjNKbGMzUXlibUZ3YTJsdSIKCQl9Cgl9Cn0K
kind: Secret
metadata:
  name: registry-amx
type: kubernetes.io/dockerconfigjson