apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: webapp-dc
spec:
  replicas: 1
  template:
    metadata:
      labels:
        webapp: webapp-verito
    spec:
      containers:
      - name: webapp-verito
        restartPolicy: Always
        image: kevout/webapp
        ports:
        - containerPort: 80
          name: webapphttp
        - containerPort: 443
          name: webapphttps
