kind: ConfigMap
apiVersion: v1
metadata:
  name: jvp-claro-connect-iam-front-cm
data: 
  claro-iam-front.conf: |
    server {
        listen   80 default;
        server_name front.claroconnect.com;
        
        location / {
          root /var/www/sites/claro-connect-iam-front;
          index index.html index.html;
          try_files $uri /src/iam/index.html?$query_string;
        }
    }