kind: ConfigMap
apiVersion: v1
metadata:
  name: jvp-claro-connect-iam-front-cm
data: 
  claro-iam-front.conf: |
    server {
        listen   80; ## listen for ipv4; this line is default and implied
        #listen   [::]:80 default ipv6only=on; ## listen for ipv6
        server_name front.claroconnect.com;
        return 301 https://$host$request_uri;
    }
    server {
        listen 443 ssl;
        server_name front.claroconnect.com;

        # Disable sendfile as per https://docs.vagrantup.com/v2/synced-folders/virtualbox.html
        sendfile off;

        # Security - Hide nginx version number in error pages and Server header
        server_tokens off;

        # Enavle virtual templates
        ssi on;

        ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
        ssl_prefer_server_ciphers on;
        ssl_ciphers "EECDH+ECDSA+AESGCM:EECDH+aRSA+AESGCM:EECDH+ECDSA+SHA256:EECDH+aRSA+SHA256:EECDH+ECDSA+SHA384:EECDH+ECDSA+SHA256:EECDH+aRSA+SHA384:EDH+aRSA+AESGCM:EDH+aRSA+SHA256:EDH+aRSA:EECDH:!aNULL:!eNULL:!MEDIUM:!LOW:!3DES:!MD5:!EXP:!PSK:!SRP:!DSS:!RC4:!SEED";

        add_header Strict-Transport-Security "max-age=31536000";

        ssl_certificate /usr/share/jitsi.claroconnect.com.pem;
        ssl_certificate_key /usr/share/jitsi.claroconnect.com.key;

        # access_log /var/log/nginx/iam.test-access.log;
        error_log  /var/log/nginx/error.log info;
        
        # Add stdout logging
        #error_log /dev/stdout info;
        access_log /dev/stdout;

        # reduce the data that needs to be sent over network
        gzip on;
        gzip_min_length 10240;
        gzip_proxied expired no-cache no-store private auth;
        gzip_types text/plain text/css text/xml application/json text/javascript application/x-javascript application/xml;
        gzip_disable "MSIE [1-6]\.";
        client_max_body_size 100m;

        ## LANDING  ------------------------------------------ ##

        location / {
            root /var/www/claro-connect-web/build;
            index index.html index.html;
            try_files $uri /$1 /index.html =404;
        }

        location ~ ^/business/faq {
            return 301 /faq;
        }

        location ~ ^/business/terms {
            return 301 https://www.clarodrive.com/mexico/legals?option=terms;
        }

        location ~ ^/terms {
            return 301 https://www.clarodrive.com/mexico/legals?option=terms;
        }

        ## IAM FRONTEND ------------------------------------------ ##

        location ~ ^/iam/images/claroconnect.svg {
            alias /var/www/claro-connect-iam-front/src/images/themes/jointalks/logo.svg;
        }
        location ~ ^/images/claroconnect.svg {
            alias /var/www/claro-connect-iam-front/src/images/themes/jointalks/logo.svg;
        }
        location ~ ^/images/mail-header.png {
            alias /var/www/claro-connect-iam-front/src/images/themes/jointalks/mail-header.png;
        }
        location ~ ^/favicon-(.+)\.png {
            alias /var/www/claro-connect-iam-front/src/images/themes/jointalks/favicon/favicon-$1.png;
        }
        location ~ ^/images/favicon.ico {
            alias /var/www/claro-connect-iam-front/src/images/themes/jointalks/favicon/favicon.ico;
        }
        location ~ ^/favicon.ico {
            alias /var/www/claro-connect-iam-front/src/images/themes/jointalks/favicon/favicon.ico;
        }

        location ~ ^/video/images/jitsilogo.png {
            try_files $uri $uri/ /images/themes/jointalks/logo.png;
        }

        location ~ ^/video/images/logo-deep-linking.png {
            try_files $uri $uri/ /images/themes/jointalks/logo.png;
        }

        location ~ /iam/(.*) {
            root /var/www/claro-connect-iam-front/src;
          index index.html index.html;
            try_files $uri /iam/index.html?$query_string;
        }

        location ~ ^/images/(.*) {
            alias /var/www/claro-connect-iam-front/src/images/$1;
        }

        location /manifest.json {
            alias /var/www/iam/public/manifest.json;
        }

        ## JITIS MEET FRONTEND ------------------------------------------ ##

        location /external_api.js {
          add_header 'Access-Control-Allow-Origin' '*';
            alias /var/www/claro-jitsi-meet/libs/external_api.min.js;
        }
        location ~ ^/libs/alwaysontop.min.js {
          add_header 'Access-Control-Allow-Origin' '*';
            try_files $uri $uri/ /video/libs/alwaysontop.min.js;
        }

        location ~ ^/css/all.css {
      add_header 'Access-Control-Allow-Origin' '*';
        try_files $uri $uri/ /video/css/all.css;
        }

        location ~ /\.ht {
            deny all;
        }

        location /config.js {
            alias /var/www/claro-jitsi-meet/config.js;
        }

        location ~ /video/(.*) {
          root /var/www/claro-jitsi-meet;
          index index.html index.html;

            location ~ ^/video/external_api.js {
                    add_header 'Access-Control-Allow-Origin' '*';
                    alias /var/www/claro-jitsi-meet/libs/external_api.min.js;
            }

            location ~ ^/video/external_api.min.map {
                    add_header 'Access-Control-Allow-Origin' '*';
                    alias /var/www/claro-jitsi-meet/libs/external_api.min.map;
            }

          location ~ ^/video/css/images/(.*)$
          {
              add_header 'Access-Control-Allow-Origin' '*';
              alias /var/www/claro-jitsi-meet/images/$1;
          }

          location ~ ^/video/(libs|css|static|images|fonts|lang|sounds|connection_optimization|.well-known)/(.*)$
          {
              add_header 'Access-Control-Allow-Origin' '*';
              alias /var/www/claro-jitsi-meet/$1/$2;
          }
          
          try_files $uri /$1 /index.html =404;
        }

        location ~ /\. {
                log_not_found off;
                deny all;
        }

        ## BOSH PROXY ------------------------------------------ ##

        location = /http-bind {
            proxy_pass http://bosh.claroconnect.com:5280/http-bind;
            proxy_set_header X-Forwarded-For $remote_addr;
            proxy_set_header Host claroconnect.com;
            proxy_ssl_trusted_certificate /usr/share/jitsi.claroconnect.com.pem;
            proxy_ssl_verify              off;
        }
    }

    server {
        listen   80; ## listen for ipv4; this line is default and implied
        #listen   [::]:80 default ipv6only=on; ## listen for ipv6
        server_name local.claroconnect.com;
        return 301 https://$host$request_uri;
    }
    server {
        listen 443 ssl;
        server_name local.claroconnect.com;

        # Disable sendfile as per https://docs.vagrantup.com/v2/synced-folders/virtualbox.html
        sendfile off;

        # Security - Hide nginx version number in error pages and Server header
        server_tokens off;

        # Enavle virtual templates
        ssi on;

        ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
        ssl_prefer_server_ciphers on;
        ssl_ciphers "EECDH+ECDSA+AESGCM:EECDH+aRSA+AESGCM:EECDH+ECDSA+SHA256:EECDH+aRSA+SHA256:EECDH+ECDSA+SHA384:EECDH+ECDSA+SHA256:EECDH+aRSA+SHA384:EDH+aRSA+AESGCM:EDH+aRSA+SHA256:EDH+aRSA:EECDH:!aNULL:!eNULL:!MEDIUM:!LOW:!3DES:!MD5:!EXP:!PSK:!SRP:!DSS:!RC4:!SEED";

        add_header Strict-Transport-Security "max-age=31536000";

        ssl_certificate /usr/share/jitsi.claroconnect.com.pem;
        ssl_certificate_key /usr/share/jitsi.claroconnect.com.key;

        # access_log /var/log/nginx/iam.test-access.log;
        error_log  /var/log/nginx/error.log info;
        
        # Add stdout logging
        #error_log /dev/stdout info;
        access_log /dev/stdout;


        # reduce the data that needs to be sent over network
        gzip on;
        gzip_min_length 10240;
        gzip_proxied expired no-cache no-store private auth;
        gzip_types text/plain text/css text/xml application/json text/javascript application/x-javascript application/xml;
        gzip_disable "MSIE [1-6]\.";
        client_max_body_size 100m;

        location ~ /\.ht {
            deny all;
        }
        location ~ \.php$ {
          if ($request_uri ~ ^/iam(.*)$ ) {
            set $request_url $1;
        }
            fastcgi_split_path_info ^(.+\.php)(/.+)$;
            fastcgi_pass php:9000;
            fastcgi_index index.php;
            include fastcgi_params;
            fastcgi_param  REQUEST_URI        $request_url;
            fastcgi_param SCRIPT_FILENAME /var/www/iam/public$fastcgi_script_name;


            fastcgi_intercept_errors off;
            fastcgi_buffer_size 16k;
            fastcgi_buffers 4 16k;
            fastcgi_connect_timeout 300;
            fastcgi_send_timeout 300;
            fastcgi_read_timeout 300;

        }


        location ~ /iam/(.*) {
          root /var/www/iam/public;
          index index.html index.html;
            try_files $uri /$1 /index.php?$query_string;
        }

        location ~ ^/images/(.*) {
          alias /var/www/iam/public/images/$1;
        }

        location ~ /\. {
                log_not_found off;
                deny all;
        }

        ## BOSH PROXY ------------------------------------------ ##

        location = /http-bind {
            if ( $request_method = OPTIONS ) {
                        add_header Access-Control-Allow-Origin '*';
                        add_header Access-Control-Allow-Methods '*';
                        add_header Access-Control-Allow-Headers '*';
                        add_header Access-Control-Allow-Credentials 'true';
                        add_header Content-Length 0;
                        add_header Content-Type text/plain;
                        return 200;
            }
            proxy_pass http://bosh.claroconnect.com:5280/http-bind;
            proxy_set_header X-Forwarded-For $remote_addr;
            proxy_set_header Host claroconnect.com;
            proxy_ssl_trusted_certificate /usr/share/jitsi.claroconnect.com.pem;
            proxy_ssl_verify              off;
        }

        # BOSH
        location = /room {
            if ( $request_method = OPTIONS ) {
                        add_header Access-Control-Allow-Origin '*';
                        add_header Access-Control-Allow-Methods '*';
                        add_header Access-Control-Allow-Headers '*';
                        add_header Access-Control-Allow-Credentials 'true';
                        add_header Content-Length 0;
                        add_header Content-Type text/plain;
                        return 200;
            }
            proxy_pass http://bosh.claroconnect.com:5280/room;
            proxy_set_header X-Forwarded-For $remote_addr;
            proxy_set_header Host claroconnect.com;
            proxy_ssl_trusted_certificate /usr/share/jitsi.claroconnect.com.pem;
            proxy_ssl_verify              off;
        }

    }
