kind: ConfigMap
apiVersion: v1
metadata:
  name: jvp-jp-iam-config-cm
data: 
  config: |
    # Jitsi Conference Focus settings
    # sets the host name of the XMPP server
    JICOFO_HOST=localhost

    # sets the XMPP domain (default: none)
    ############################ En caso de ser necesario ajustar dominio #####################
    JICOFO_HOSTNAME=claroconnect.com

    # sets the secret used to authenticate as an XMPP component
    JICOFO_SECRET=xP6fgU#l

    # sets the port to use for the XMPP component connection
    JICOFO_PORT=5347

    # sets the XMPP domain name to use for XMPP user logins
    ############################ En caso de ser necesario ajustar dominio #####################
    JICOFO_AUTH_DOMAIN=auth.claroconnect.com

    # sets the username to use for XMPP user logins
    JICOFO_AUTH_USER=focus

    # sets the password to use for XMPP user logins
    JICOFO_AUTH_PASSWORD=fa8DmGQk

    # extra options to pass to the jicofo daemon
    JICOFO_OPTS=""

    # adds java system props that are passed to jicofo (default are for home and logging config file)
    JAVA_SYS_PROPS="-Dnet.java.sip.communicator.SC_HOME_DIR_LOCATION=/etc/jitsi -Dnet.java.sip.communicator.SC_HOME_DIR_NAME=jicofo -Dnet.java.sip.communicator.SC_LOG_DIR_LOCATION=/var/log/jitsi -Djava.util.logging.config.file=/etc/jitsi/jicofo/logging.properties"