- hosts: all
  tasks:
  
    - name: "Copy"
      copy: src=../scripts/rhel7_hardening-2020.sh dest=/tmp/01.sh mode="u=rwx,g-,o-"

    - name: "Running Rhel7 Hardening"
      shell: "/tmp/01.sh"

    - name: "All forwarding on"
      replace:
        path: /etc/sysctl.conf
        regexp: 'net.ipv4.conf.all.forwarding=.*'
        replace: 'net.ipv4.conf.all.forwarding=1'
    
    - name: "Ip forward on"
      replace:
        path: /etc/sysctl.conf
        regexp: 'net.ipv4.ip_forward=.*'
        replace: 'net.ipv4.ip_forward=1'
    
    - name: "Apply sysctl changes"
      shell : sysctl -p
      register: sysct_changed